spring:
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}/?retryWrites=true&w=majority&appName=${MONGODB_APP_NAME}
      database: ${MONGODB_DATABASE}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

server:
  port: ${SERVER_PORT}

app:
  frontend:
    base-url: ${FRONTEND_BASE_URL}